# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2b9287ea0a64c5629f905ede9680cffdc8d6320a147e3de73a2c8723d699d09b22455ba6f15f219130c03d3b996fa29f3f56bb0095318a8b0db5d47e7bef74

test:
  secret_key_base: 01c15cf548a05007dcef9d05dd79da1dc20c9c2fd7e7b918698b399c2745ffcb1bd2ea18cf36dc3545b40d595a28bf55cafced0ad9e9ce82764beaed15605f45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
